# Generated by Django 3.1 on 2020-08-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200825_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='frist_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
